### PR TITLE
Add invoke for redirector

### PR DESCRIPTION
**Pull request by merqlove**

### CODE REVIEW

**Comment by chenkie** [comment]
Thanks for this!

Why are you returning `invokeToken` and `invokeRedirector` from the service though? Those should only be used inside the service itself.

**Comment by merqlove** [comment]
I found it useful to have in this service, for DRY.
It helps when we need to be sure that token is updated before some action.
For example, as i do:
```
  $rootScope.$on('authenticated', (event, data) => {
    store.set('authToken', data.jwt);
    $rootScope.currentUser = data.user;
    const token = authManager.invokeToken();
    }

    $state.go('app.tasks.list');
  });
```

**Comment by chenkie** [comment]
Ok, that's a good point. If we keep those methods public then my preference would be to rename `invokeToken` to `getToken` and `invokeRedirector` to `redirect`. I think those names will seem a bit less weird as the word "invoke" is a bit contextual. Thoughts?

**Comment by merqlove** [comment]
Sure, good idea. I will amend it.

**Pull request merged**
