### PR TITLE
Add support for white listed domain as regexp

### PR DESCRIPTION
**Pull request by fvilers**
This PR should resolve the issue mentioned [here](https://github.com/auth0/angular-jwt/issues/109).

### CODE REVIEW

**Comment by chenkie** [comment]
Thanks for your PR! I will review this shortly.

**Comment by fvilers** [comment]
@chenkie Is there any blocking points to merge this PR? Can I help?

**Comment by dwightdegroff** [comment]
Any chance of this moving forward in the near future?

**Comment by chenkie** [comment]
Looking good, thanks for this @fvilers :) I just need to fix up some tests and then I'll publish.

**Pull request merged**
