### PR TITLE
Add config option to allow token to be set as a url param instead of a header

### PR DESCRIPTION
**Pull request by doshprompt**
Defaults to standard header format if not overridden,
otherwise will add access_token=<token> to the url

[Review on Reviewable](https://reviewable.io/reviews/auth0/angular-jwt/31)

### CODE REVIEW

**Comment by doshprompt** [comment]
If this commit is merged, imo the version should be bumped to `0.0.7`

Also, please note that the diff for the dist files seems to contain some changes that are not part of my commit's code but rather, they show up due to some missing synchronization in a previous PR merge.

**Comment by mikedon** [comment]
any movement on this?

**Comment by mgonto** [comment]
This looks really good :).

@doshprompt can you rebase with master now? I'll merge afterwards.

Thanks!

**Comment by doshprompt** [comment]
@mgonto done, sorry I had some issues, please can you merge and then bump the version to `0.0.9`

**Comment by mgonto** [comment]
Yep.

I have one more remaining PR, I'll bump it in the next day :).

Thanks again!

**Comment by mgonto** [comment]
Pushed as 0.0.9

**Comment by doshprompt** [comment]
Thanks :)

**Pull request merged**
